// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoeEw8FzOAIF2i8EIdPO7S5AKOWupy6fw',
    appId: '1:504984880094:web:1f4b1eb0e16a5ed530d34f',
    messagingSenderId: '504984880094',
    projectId: 'portifolio-bash',
    authDomain: 'portifolio-bash.firebaseapp.com',
    storageBucket: 'portifolio-bash.firebasestorage.app',
    measurementId: 'G-40LE21CHZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYph_wF0l6KpT0lh0JqBIEQlOXRklQsJw',
    appId: '1:504984880094:android:b4b4792f4332a31e30d34f',
    messagingSenderId: '504984880094',
    projectId: 'portifolio-bash',
    storageBucket: 'portifolio-bash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtCWJ0nSYPBcoDS7wSRl-9AX59jqrLLJ4',
    appId: '1:504984880094:ios:457e08c41bcc064a30d34f',
    messagingSenderId: '504984880094',
    projectId: 'portifolio-bash',
    storageBucket: 'portifolio-bash.firebasestorage.app',
    iosBundleId: 'com.example.adminportifolioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtCWJ0nSYPBcoDS7wSRl-9AX59jqrLLJ4',
    appId: '1:504984880094:ios:457e08c41bcc064a30d34f',
    messagingSenderId: '504984880094',
    projectId: 'portifolio-bash',
    storageBucket: 'portifolio-bash.firebasestorage.app',
    iosBundleId: 'com.example.adminportifolioapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoeEw8FzOAIF2i8EIdPO7S5AKOWupy6fw',
    appId: '1:504984880094:web:c14ad92d84aed26030d34f',
    messagingSenderId: '504984880094',
    projectId: 'portifolio-bash',
    authDomain: 'portifolio-bash.firebaseapp.com',
    storageBucket: 'portifolio-bash.firebasestorage.app',
    measurementId: 'G-XB5F0V8619',
  );
}
